### ISSUE TITLE
[Bug] incorrect `call_success` value on Decoded Contract Table

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#1765]
[This query](https://dune.com/queries/1398319?d=1) returns false

```sql
select call_success from gnosis_protocol_v2_ethereum.GPv2Settlement_call_settle
where call_tx_hash = '0x96c51fae0b8cc6c4d45f8a81a1c7dbe225a3a22ad08c32ca3170c2409c64c891'
```

but this transaction was mined:

https://etherscan.io/tx/0x96c51fae0b8cc6c4d45f8a81a1c7dbe225a3a22ad08c32ca3170c2409c64c891

![Screen Shot 2022-10-13 at 12 10 09 PM](https://user-images.githubusercontent.com/11778116/195569383-a79f605c-b4a5-4ff0-88d1-39366f55a3ce.png)

A suggested quick fix would be (sorry for postgres syntax).

```sql
UPDATE gnosis_protocol_v2_ethereum.GPv2Settlement_call_settle
SET call_success = true
WHERE call_tx_hash = '0x96c51fae0b8cc6c4d45f8a81a1c7dbe225a3a22ad08c32ca3170c2409c64c891'
```
but I would also be curious to know why this value is incorrect...

Furthermore this affects the `cow_protocol_ethereum` trades and batches tables (which would need to be refreshed).

**Comment by bh2smith** [comment]
I [checked for others](https://dune.com/queries/1399121?d=1&category=decoded_project&namespace=gnosis_protocol_v2&blockchains=ethereum&contract=GPv2Settlement) and this is the only one

**Comment by 0xRobin** [comment]
I took a look at the traces table, which from my understanding is the source (or uses the same source) for the decoded call tables.

Looking at all the traces (so not CoW specific)
I found **520 more examples** which I believe to be wrong (I checked a couple manually)
https://dune.com/queries/1414050?d=1
These are found looking for `tx_success=true, success=false, trace_address={}`, which should normally never be the case?

They seem to be centered around a couple blocks with lots of mistakes on 05/08/2022 and now more recently more singular faulty traces since 14/09/2022
![image](https://user-images.githubusercontent.com/83790096/196057204-e5ae9e75-4b56-4ec4-be7f-c8641b5db084.png)

**Comment by bh2smith** [comment]
Nice investigation here @0xRobin. It didn't even cross my mind to check this for everything. Really good thinking and nice results (no matter how unfortunate they are). 

What can we do next to get this sorted? Seems like a simple "update" won't fix the root cause.

**Comment by 0xRobin** [comment]
Not sure..
Probably pester Dune engineers and hope they find the root cause? 
These data faults are scary to see though, as it might be the case that there are more lower level call traces that have incorrect data. I'm not sure how we could try and find those..

We should probably also verify if only the success column is affected or if there are other inconsistencies.

@jeff-dude can you get the correct pair of Dune eyes on this? 🙏

**Comment by vegarsti** [comment]
Thanks so much for reporting this, this does indeed seem to be wrong! The reason we're setting these traces as unsuccessful is that they have a non-null error. The `error` column is not null for all rows in https://dune.com/queries/1414050?d=1.

I'm not sure why we have a non-null error on these traces, though. I assume they can't be successful while also having errors? 🤔

**Comment by bh2smith** [comment]
If I look specifically at the transaction related to cow protocol:

https://etherscan.io/tx/0x96c51fae0b8cc6c4d45f8a81a1c7dbe225a3a22ad08c32ca3170c2409c64c891#internal

The query shared shows the error column as "Reverted" which it most certainly was not. There are no sub calls to contracts which reverted either (checking the "internal transactions"). 

I could dig into tenderly and go step by step through to see what could have been causing this


One thing I noticed in [this transaction](https://etherscan.io/tx/0x4915a0aef5495ef7eecbcef8278019a902dcff5d32fd85c0ad0c5d65b2b76ef7) is that the error says "Out of Gas" and that this particular transaction used exactly 100% (every single unit of WEI given):

<img width="600" alt="Screenshot 2022-10-17 at 11 11 16 AM" src="https://user-images.githubusercontent.com/11778116/196138287-f3d55266-824b-4f70-9f13-9f9b85ad628d.png">


Same for [this one](https://etherscan.io/tx/0x0a1b196b0e1ae0c3fc20c11daa422b753c5f4618931caa391ab9b5e06d3faacd) (both having identical gas used too)

It seems to me the Out of Gas Error happens when the `gasLimit == gasUsed`

Unfortunately, this theory does not hold up ([example](https://etherscan.io/tx/0x546c101f3d11c27dd3b46948b53cc7f6b25e6104abe9ff9372ae875cad0c55eb))


I do notice, however that the "Out Of Gas" errors all have null for gas used.

**Comment by bh2smith** [comment]
Out of general curiority I forked the query shared by @0xRobin to see if the same phenomena was happening on other networks.

I have only checked Gnosis Chain so far (where there is only 1 occurrence of this)

https://dune.com/queries/1427715?category=canonical&Blockchain_e15077=gnosis

The query is now parameterized so we can change the network and rerun.

**Comment by vegarsti** [comment]
Thanks so much for identifying this issue @bh2smith! We've found the root cause and are working to fix it now. Will let you know when it is fixed.

**Comment by 0xRobin** [comment]
@vegarsti awesome! I'm curious what was the exact root cause?

**Comment by bh2smith** [comment]
How's this coming along, I would also be interested to know what the issue was/is.

**Comment by vegarsti** [comment]
The bug is fixed now! https://dune.com/queries/1508305?d=1

Sorry for the late response here guys: We had to do a complete backfill of our data starting from data from node providers, so it took a bit long.

**Comment by bh2smith** [comment]
This is fantastic news! Thanks for this. Unfortunately however, this fix does not appear to have triggered an update of the table from this spell which is still missing the transaction hash initially posted in the issue. 

https://github.com/duneanalytics/spellbook/pull/1752

Shouldn't changes to dependant table trigger some sort of refresh?
